/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Units;
import DesignPatern.Observable;
import DesignPatern.Observer;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Submarine extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Submarine
     */
    private final String name;
    private final Observable control;
    
    public Submarine() {
        initComponents();
        
        control = Observable.getInstance();
        name = "Submarine";
        setTitle("Submarine");
        setLocation(50,500);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnSonar = new javax.swing.JButton();
        btnTomahawk = new javax.swing.JButton();
        btnTrident = new javax.swing.JButton();
        scrlInbox = new javax.swing.JScrollPane();
        txtInBox = new javax.swing.JTextArea();
        scrlSendBox = new javax.swing.JScrollPane();
        txtSendBox = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblSoldier = new javax.swing.JLabel();
        lblAmmo = new javax.swing.JLabel();
        spnrSoldier = new javax.swing.JSpinner();
        spnrAmmo = new javax.swing.JSpinner();
        sldrFuel = new javax.swing.JSlider();
        chckPosition = new javax.swing.JCheckBox();
        lblTitle = new javax.swing.JLabel();
        lblTitleBack = new javax.swing.JLabel();
        lblFuel = new javax.swing.JLabel();
        sldrOxygen = new javax.swing.JSlider();
        lblOxygen = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArea.setFont(lblArea.getFont().deriveFont(lblArea.getFont().getStyle() | java.awt.Font.BOLD, 13));
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("Area Not Cleared");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 128, 29));

        btnShoot.setEnabled(false);
        btnShoot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnShoot.setText("Shoot");
        getContentPane().add(btnShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        btnSonar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSonar.setText("Sonar Operation");
        btnSonar.setEnabled(false);
        getContentPane().add(btnSonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, -1));

        btnTomahawk.setEnabled(false);
        btnTomahawk.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTomahawk.setText("Tomahawk Missile");
        getContentPane().add(btnTomahawk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        btnTrident.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTrident.setText("Trident-2 Missile");
        btnTrident.setEnabled(false);
        getContentPane().add(btnTrident, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, -1));

        txtInBox.setEditable(false);
        txtInBox.setBackground(new java.awt.Color(242, 242, 242));
        txtInBox.setColumns(20);
        txtInBox.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtInBox.setRows(5);
        scrlInbox.setViewportView(txtInBox);

        getContentPane().add(scrlInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 560, 139));

        txtSendBox.setBackground(new java.awt.Color(242, 242, 242));
        txtSendBox.setColumns(20);
        txtSendBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSendBox.setRows(5);
        txtSendBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSendBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSendBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSendBoxKeyTyped(evt);
            }
        });
        scrlSendBox.setViewportView(txtSendBox);

        getContentPane().add(scrlSendBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 470, 30));

        btnSend.setEnabled(false);
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSend.setText("Send");
        btnSend.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 70, 30));

        lblSoldier.setFont(lblSoldier.getFont().deriveFont(lblSoldier.getFont().getStyle() | java.awt.Font.BOLD, 13));
        lblSoldier.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoldier.setText("Soldier Count");
        getContentPane().add(lblSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 123, 29));

        lblAmmo.setFont(lblAmmo.getFont().deriveFont(lblAmmo.getFont().getStyle() | java.awt.Font.BOLD, 13));
        lblAmmo.setForeground(new java.awt.Color(255, 255, 255));
        lblAmmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmmo.setText("Ammo Count");
        getContentPane().add(lblAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 123, 29));

        spnrSoldier.setValue(10);
        getContentPane().add(spnrSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 70, -1));

        spnrAmmo.setValue(50);
        getContentPane().add(spnrAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 70, -1));

        sldrFuel.setOpaque(false);
        sldrFuel.setBackground(new java.awt.Color(255, 255, 255));
        sldrFuel.setForeground(new java.awt.Color(255, 255, 255));
        sldrFuel.setMajorTickSpacing(20);
        sldrFuel.setMinorTickSpacing(10);
        sldrFuel.setOrientation(javax.swing.JSlider.VERTICAL);
        sldrFuel.setPaintLabels(true);
        sldrFuel.setPaintTicks(true);
        sldrFuel.setValue(100);
        getContentPane().add(sldrFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, 340));

        chckPosition.setOpaque(false);
        chckPosition.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        chckPosition.setForeground(new java.awt.Color(255, 255, 255));
        chckPosition.setText("Position");
        chckPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckPositionActionPerformed(evt);
            }
        });
        getContentPane().add(chckPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Submarine");
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        lblTitleBack.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitleBack.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cama.jpg"))); // NOI18N
        lblTitleBack.setText("TANK");
        lblTitleBack.setToolTipText("");
        lblTitleBack.setMinimumSize(new java.awt.Dimension(300, 980));
        lblTitleBack.setPreferredSize(new java.awt.Dimension(300, 980));
        getContentPane().add(lblTitleBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        lblFuel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFuel.setForeground(new java.awt.Color(255, 255, 255));
        lblFuel.setText("Fuel ⛽");
        getContentPane().add(lblFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 50, 20));

        sldrOxygen.setOpaque(false);
        sldrOxygen.setBackground(new java.awt.Color(255, 255, 255));
        sldrOxygen.setForeground(new java.awt.Color(255, 255, 255));
        sldrOxygen.setMajorTickSpacing(20);
        sldrOxygen.setMinorTickSpacing(10);
        sldrOxygen.setOrientation(javax.swing.JSlider.VERTICAL);
        sldrOxygen.setPaintLabels(true);
        sldrOxygen.setPaintTicks(true);
        sldrOxygen.setValue(100);
        getContentPane().add(sldrOxygen, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, 340));

        lblOxygen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblOxygen.setForeground(new java.awt.Color(255, 255, 255));
        lblOxygen.setText("Oxygen");
        getContentPane().add(lblOxygen, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 50, 20));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/subMarine.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        control.SendToMain(name + " : " + txtSendBox.getText());
        txtSendBox.setText("");
        btnSend.setEnabled(false);
    }//GEN-LAST:event_btnSendActionPerformed

    private void chckPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckPositionActionPerformed
        setButtons(control.getStrength());
    }//GEN-LAST:event_chckPositionActionPerformed

    private void txtSendBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendBoxKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER && !(txtSendBox.getText().equals(""))) {
            evt.consume();
            control.SendToMain(name + " : " + txtSendBox.getText());
            txtSendBox.setText("");
            btnSend.setEnabled(false);
        }else if(!(txtSendBox.getText().equals(""))){
            btnSend.setEnabled(true);
        }else{
            btnSend.setEnabled(false);
        }
    }//GEN-LAST:event_txtSendBoxKeyPressed

    private void txtSendBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendBoxKeyReleased
       if(!(txtSendBox.getText().equals(""))){
            btnSend.setEnabled(true);
        }else{
            btnSend.setEnabled(false);
	}
    }//GEN-LAST:event_txtSendBoxKeyReleased

    private void txtSendBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendBoxKeyTyped
        if(!(txtSendBox.getText().equals(""))){
            btnSend.setEnabled(true);
        }else{
            btnSend.setEnabled(false);
	}
    }//GEN-LAST:event_txtSendBoxKeyTyped
    
    @Override
    public void getMsg(String msg){
        txtInBox.append("\n" + msg);
    }
    
    /**
     *
     * @param bol
     */
    @Override
    public void UpdateArea(Boolean bol){
        if (bol == true){
            lblArea.setText("Area Cleared");
        }else{
            lblArea.setText("Area Not Cleared");
        }
    }
    
    @Override
    public void setButtons(int value){
        if (chckPosition.isSelected()){
                if (value>=20){
                    btnShoot.setEnabled(true);
                }else{
                    btnShoot.setEnabled(false);
                }
                if(value>=40){
                    btnSonar.setEnabled(true);
                }else{
                    btnSonar.setEnabled(false);
                }
                if(value>=60){
                    btnTomahawk.setEnabled(true);
                }else{
                    btnTomahawk.setEnabled(false);
                }
                if(value>=80){
                    btnTrident.setEnabled(true);
                }else{
                    btnTrident.setEnabled(false);
                }
        }else{
            btnShoot.setEnabled(false);
            btnSonar.setEnabled(false);
            btnTomahawk.setEnabled(false);
            btnTrident.setEnabled(false);
        }
    }
    
    @Override
    public String getName(){
        return name;
    }
    
    @Override
    public void giveInfo(int value){
        String btnInfo = "" ;
        if (chckPosition.isSelected()){
                if (value>=20){
                    btnInfo += "Shooting Button Available.. \n";
                }
                if(value>=40){
                    btnInfo += "Sonar Operation Available.. \n";
                }
                if(value>=60){
                   btnInfo += "Tomahawk Missile Available.. \n";
                }
                if(value>=80){
                   btnInfo += "Trident-2 Available.. \n";
                }
                
        }
        String count = "Soldier Count : " + spnrSoldier.getValue() +"\nAmmo Count :" + spnrAmmo.getValue() + "\nFuel Availability : " + sldrFuel.getValue() + "%\nOxygen Level : " + sldrOxygen.getValue() + "%\n" ;
        JOptionPane.showMessageDialog(null, (count + btnInfo) , " Submarine  Info", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonar;
    private javax.swing.JButton btnTomahawk;
    private javax.swing.JButton btnTrident;
    private javax.swing.JCheckBox chckPosition;
    private javax.swing.JLabel lblAmmo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblOxygen;
    private javax.swing.JLabel lblSoldier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleBack;
    private javax.swing.JScrollPane scrlInbox;
    private javax.swing.JScrollPane scrlSendBox;
    private javax.swing.JSlider sldrFuel;
    private javax.swing.JSlider sldrOxygen;
    private javax.swing.JSpinner spnrAmmo;
    private javax.swing.JSpinner spnrSoldier;
    private javax.swing.JTextArea txtInBox;
    private javax.swing.JTextArea txtSendBox;
    // End of variables declaration//GEN-END:variables
}
