/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Units;

import DesignPatern.Observable;
import DesignPatern.Observer;
import Utils.UIManager;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Dell
 */
public class Tank extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Tank
     */
    private final String name;
    private final Observable control;
    
    public Tank() {
        initComponents();
        
        control = Observable.getInstance();
        name = "Tank";
        setTitle("Defence System - " + name);
        setResizable(false);
        
        // Apply modern UI styling
        applyUIStyles();
        
        // Create panels for better organization
        createPanels();
    }
    
    /**
     * Apply consistent UI styling to components
     */
    private void applyUIStyles() {
        // Style the background and overall appearance
        getContentPane().setBackground(UIManager.BACKGROUND_DARK);
        
        // Style the buttons
        UIManager.styleButton(btnShoot);
        UIManager.styleButton(btnMissile);
        UIManager.styleButton(btnRotate);
        UIManager.styleButton(btnRedar);
        UIManager.styleButton(btnSend);
        
        // Style the labels
        lblTitle.setFont(UIManager.TITLE_FONT);
        lblTitle.setForeground(UIManager.TEXT_LIGHT);
        
        lblArea.setFont(UIManager.SUBTITLE_FONT);
        lblArea.setForeground(UIManager.TEXT_LIGHT);
        
        lblFuel.setFont(UIManager.TEXT_FONT);
        lblFuel.setForeground(UIManager.TEXT_LIGHT);
        
        lblSoldier.setFont(UIManager.TEXT_FONT);
        lblSoldier.setForeground(UIManager.TEXT_LIGHT);
        
        lblAmmo.setFont(UIManager.TEXT_FONT);
        lblAmmo.setForeground(UIManager.TEXT_LIGHT);
        
        // Style text components
        UIManager.styleTextComponent(txtInBox);
        UIManager.styleTextComponent(txtSendBox);
        
        // Style slider
        UIManager.styleSlider(sldrFuel);
        
        // Style checkbox
        UIManager.styleCheckBox(chckPosition);
        
        // Add tooltips
        btnShoot.setToolTipText("Fire standard ammunition");
        btnMissile.setToolTipText("Launch a guided missile");
        btnRotate.setToolTipText("Rotate the turret for directional firing");
        btnRedar.setToolTipText("Activate radar to scan surroundings");
        btnSend.setToolTipText("Send message to control center");
        chckPosition.setToolTipText("Toggle tank position to enable operations");
        sldrFuel.setToolTipText("Current fuel level");
        spnrAmmo.setToolTipText("Ammunition count");
        spnrSoldier.setToolTipText("Number of crew members");
    }
    
    /**
     * Create panels to group related controls
     */
    private void createPanels() {
        // Create weapons panel
        JPanel weaponsPanel = new JPanel();
        weaponsPanel.setBorder(BorderFactory.createTitledBorder(
                UIManager.PANEL_BORDER, "Weapons Control", 
                TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.DEFAULT_POSITION, 
                UIManager.SUBTITLE_FONT, Color.WHITE));
        weaponsPanel.setOpaque(false);
        
        // Create resources panel
        JPanel resourcesPanel = new JPanel();
        resourcesPanel.setBorder(BorderFactory.createTitledBorder(
                UIManager.PANEL_BORDER, "Resources", 
                TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.DEFAULT_POSITION, 
                UIManager.SUBTITLE_FONT, Color.WHITE));
        resourcesPanel.setOpaque(false);
        
        // Create communications panel
        JPanel commsPanel = new JPanel();
        commsPanel.setBorder(BorderFactory.createTitledBorder(
                UIManager.PANEL_BORDER, "Communications", 
                TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.DEFAULT_POSITION, 
                UIManager.SUBTITLE_FONT, Color.WHITE));
        commsPanel.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        btnRotate = new javax.swing.JButton();
        scrlInbox = new javax.swing.JScrollPane();
        txtInBox = new javax.swing.JTextArea();
        scrlSendBox = new javax.swing.JScrollPane();
        txtSendBox = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblSoldier = new javax.swing.JLabel();
        lblAmmo = new javax.swing.JLabel();
        spnrSoldier = new javax.swing.JSpinner();
        spnrAmmo = new javax.swing.JSpinner();
        sldrFuel = new javax.swing.JSlider();
        chckPosition = new javax.swing.JCheckBox();
        btnRedar = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblTitleBack = new javax.swing.JLabel();
        lblFuel = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArea.setFont(lblArea.getFont().deriveFont(lblArea.getFont().getStyle() | java.awt.Font.BOLD, 13));
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("Area Not Cleared");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 60, 130, 29));

        btnShoot.setEnabled(false);
        btnShoot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnShoot.setText("Shoot");
        getContentPane().add(btnShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        btnMissile.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnMissile.setText("Missile Operation");
        btnMissile.setEnabled(false);
        getContentPane().add(btnMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, -1));

        btnRotate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRotate.setText("Rotate Shooting");
        btnRotate.setEnabled(false);
        getContentPane().add(btnRotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));

        txtInBox.setEditable(false);
        txtInBox.setBackground(new java.awt.Color(242, 242, 242));
        txtInBox.setColumns(20);
        txtInBox.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtInBox.setRows(5);
        scrlInbox.setViewportView(txtInBox);

        getContentPane().add(scrlInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 580, 139));

        txtSendBox.setBackground(new java.awt.Color(242, 242, 242));
        txtSendBox.setColumns(20);
        txtSendBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSendBox.setRows(5);
        txtSendBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSendBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSendBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSendBoxKeyTyped(evt);
            }
        });
        scrlSendBox.setViewportView(txtSendBox);

        getContentPane().add(scrlSendBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 490, 30));

        btnSend.setEnabled(false);
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSend.setText("Send");
        btnSend.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 81, 30));

        lblSoldier.setFont(lblSoldier.getFont().deriveFont(lblSoldier.getFont().getStyle() | java.awt.Font.BOLD, 13));
        lblSoldier.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoldier.setText("Soldier Count");
        getContentPane().add(lblSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 123, 29));

        lblAmmo.setFont(lblAmmo.getFont().deriveFont(lblAmmo.getFont().getStyle() | java.awt.Font.BOLD, 13));
        lblAmmo.setForeground(new java.awt.Color(255, 255, 255));
        lblAmmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmmo.setText("Ammo Count");
        getContentPane().add(lblAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 123, 29));

        spnrSoldier.setValue(10);
        getContentPane().add(spnrSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 70, -1));

        spnrAmmo.setValue(500);
        getContentPane().add(spnrAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 70, -1));

        sldrFuel.setOpaque(false);
        sldrFuel.setBackground(new java.awt.Color(255, 255, 255));
        sldrFuel.setForeground(new java.awt.Color(255, 255, 255));
        sldrFuel.setMajorTickSpacing(20);
        sldrFuel.setMinorTickSpacing(10);
        sldrFuel.setOrientation(javax.swing.JSlider.VERTICAL);
        sldrFuel.setPaintLabels(true);
        sldrFuel.setPaintTicks(true);
        sldrFuel.setValue(100);
        getContentPane().add(sldrFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, 340));

        chckPosition.setOpaque(false);
        chckPosition.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        chckPosition.setForeground(new java.awt.Color(255, 255, 255));
        chckPosition.setText("Position");
        chckPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckPositionActionPerformed(evt);
            }
        });
        getContentPane().add(chckPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        btnRedar.setEnabled(false);
        btnRedar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRedar.setText("Redar Operation");
        getContentPane().add(btnRedar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("TANK");
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        lblTitleBack.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitleBack.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cama.jpg"))); // NOI18N
        lblTitleBack.setText("TANK");
        lblTitleBack.setToolTipText("");
        lblTitleBack.setMinimumSize(new java.awt.Dimension(300, 980));
        lblTitleBack.setPreferredSize(new java.awt.Dimension(300, 980));
        getContentPane().add(lblTitleBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 50));

        lblFuel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFuel.setForeground(new java.awt.Color(255, 255, 255));
        lblFuel.setText("Fuel ⛽");
        getContentPane().add(lblFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 50, 20));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tank.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -30, 940, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckPositionActionPerformed
        setButtons(control.getStrength());
    }//GEN-LAST:event_chckPositionActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        control.SendToMain(name + " : " + txtSendBox.getText());
        txtSendBox.setText("");
        btnSend.setEnabled(false);
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtSendBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendBoxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !(txtSendBox.getText().equals(""))) {
            evt.consume();
            control.SendToMain(name + " : " + txtSendBox.getText());
            txtSendBox.setText("");
            btnSend.setEnabled(false);
        }else if(!(txtSendBox.getText().equals(""))){
            btnSend.setEnabled(true);
        }else{
            btnSend.setEnabled(false);
        }
    }//GEN-LAST:event_txtSendBoxKeyPressed

    private void txtSendBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendBoxKeyReleased
        if(!(txtSendBox.getText().equals(""))){
            btnSend.setEnabled(true);
        }else{
            btnSend.setEnabled(false);
        }
    }//GEN-LAST:event_txtSendBoxKeyReleased

    private void txtSendBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendBoxKeyTyped
        if(!(txtSendBox.getText().equals(""))){
            btnSend.setEnabled(true);
        }else{
            btnSend.setEnabled(false);
        }
    }//GEN-LAST:event_txtSendBoxKeyTyped

    @Override
    public void getMsg(String msg){
        txtInBox.append("\n" + msg);
    }
    
    @Override
    public void UpdateArea(Boolean bol){
        if (bol == true){
            lblArea.setText("Area Cleared");
        }else{
            lblArea.setText("Area Not Cleared");
        }
    }
    
    @Override
    public void setButtons(int value){
        if (chckPosition.isSelected()){
            if (value>=20){
                btnShoot.setEnabled(true);
            }else{
                btnShoot.setEnabled(false);
            }
            if(value>=40){
                btnMissile.setEnabled(true);
            }else{
                btnMissile.setEnabled(false);
            }
            if(value>=60){
                btnRotate.setEnabled(true);
            }else{
                btnRotate.setEnabled(false);
            }
            if(value>=80){
                btnRedar.setEnabled(true);
            }else{
                btnRedar.setEnabled(false);
            }
        }else{
            btnShoot.setEnabled(false);
            btnMissile.setEnabled(false);
            btnRotate.setEnabled(false);
            btnRedar.setEnabled(false);
        }
    }
    
    @Override
    public String getName(){
        return name;
    }
    
    @Override
    public void giveInfo(int value){
        JOptionPane.showMessageDialog(null, "Fuel = " + sldrFuel.getValue() + "%\nSoldier Count = " + spnrSoldier.getValue() + "\nAmmo Count = " + spnrAmmo.getValue());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnRedar;
    private javax.swing.JButton btnRotate;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JCheckBox chckPosition;
    private javax.swing.JLabel lblAmmo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblSoldier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleBack;
    private javax.swing.JScrollPane scrlInbox;
    private javax.swing.JScrollPane scrlSendBox;
    private javax.swing.JSlider sldrFuel;
    private javax.swing.JSpinner spnrAmmo;
    private javax.swing.JSpinner spnrSoldier;
    private javax.swing.JTextArea txtInBox;
    private javax.swing.JTextArea txtSendBox;
    // End of variables declaration//GEN-END:variables
}
